### PR TITLE
deimos.X11.Xlib: Fix constness

### PR DESCRIPTION
**Pull request by CyberShadow**
Adds missing const qualifiers from function parameters.

### CODE REVIEW

**Comment by schveiguy** [comment]
Not sure about this one. Original headers do not have const specified in at least some of the functions (I checked XLoadQueryFont). I understand the point is to allow passing string literals, but it's difficult to verify that these are correct. The documentation doesn't say that the strings won't be changed. Is there any X functions which do change char * arguments? If not, then probably we can just merge this.

**Comment by CyberShadow** [comment]
I thought I was pretty meticulous about copying the headers' constness.

> Original headers do not have const specified in at least some of the functions (I checked XLoadQueryFont).

Um, where did you look? I used the header file from this project as reference, and it clearly does have a const qualifier in XLoadQueryFont: https://github.com/D-Programming-Deimos/libX11/blob/master/c/X11/Xlib.h#L1402-L1405

**Comment by CyberShadow** [comment]
> Is there any X functions which do change char * arguments?

Yes, there are some functions which e.g. query the names of keysyms and such, for which I've obviously not added const qualifiers.

**Comment by schveiguy** [comment]
Sorry, I thought they were ubiquitously the same. I looked via google and found this: http://www.x.org/archive/X11R7.5/doc/man/man3/XChar2b.3.html

Which I have no idea whether this has changed or is authoratative (or even if it is accurate when it comes to the docs vs. the actual header).

I'll assume this is correct then.

**Comment by CyberShadow** [comment]
Thanks :)

**Pull request merged**
